### ISSUE TITLE
I would like a nord mode.

### ISSUE THREAD

**Issue by molio** [tablacus/TablacusExplorer#713]
If possible, could you add a nord (**deep blue**) or ever forest (**deep green**) mode in addition to the dark mode?
The current dark mode is too **black**, although it can't be helped because Windows itself is like that. It is **not** dark.
Windows has been getting whiter since 11, so we can't expect MS to do anything about it.
I don't think it is realistic to add a theme feature because of the amount of work involved.

For these reasons, I would appreciate it if you could add a blue or green mode.

If it is easy for Gaku san to customize with CSS add-ons, it would be great if you could give us a sample.Also, if it is easy to add theme add-ons, that would be great too.

[https://www.nordtheme.com/](url)
[https://www.gnome-look.org/p/1695467/](url)
Thank you very much for your time.

**Comment by tablacus** [comment]
Please try to use the two add-ons "Color" and "User style sheet" instead of the "Dark Mode" add-on.

You can change the color of the list view and tree view using the "Color" add-on.

Color
![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/421f8375-e43d-4600-8dc1-17c0665cfb97)

For other parts, try changing the colors in the style sheet below.

User style sheet
![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/1c51b782-b09f-4c90-bea7-d6d1977f8f97)

```css
:root {
  color-scheme: dark;
}

body {
  color: #fff;
  background-color: #202020;
}

input[type="text"], input[type="number"], select, textarea {
  color: #fff;
  background-color: #191919;
  border: solid 1px #555;
}

.menu {
  color: #fff;
}

.hoverbutton, .activebutton {
  color: #fff;
  background-color: #555;
  border: solid 1px #777;
}

.hovermenu, .activemenu {
  color: #fff;
  background-color: #555;
  border: 1px solid #555;
}

.tab, .tab2, .tab3 {
  color: #fff;
  background: #000;
  border: 1px solid #555;
}

.tab:hover, .tab2:hover, .tab3:hover {
  box-shadow: 0 0 0 9em rgba(134, 134, 134, 0.5) inset;
  opacity: 1;
  filter: alpha(style=0,opacity=100);
}

.activetab {
  color: #fff;
  background-color: #555;
  border: 1px solid #555;
}

.treebutton, .treespace, .disabled {
  color: #999;
}
.breadcrumb {
  color: #fff;
  background-color: #191919;
}

.separator {
  color: #666;
}

.panel, .color, .block {
  border: 1px solid #666;
}

.group {
  border-left: 1px solid #666;
  border-right: 1px solid #666;
  border-bottom: 1px solid #666;
}

.oddline {
  color: #fff;
  background-color: #333;
}

.window {
  color: #fff;
  background-color: #202020;
  border: 1px solid #666;
}

.window td {
  border: 1px solid #666;
}

.text1 {
  color: #fff;
  background-color: #000;
  border: 1px solid #666;
}

.pane {
  color: #fff;
  background-color: #202020;
  border: 1px solid #666;
}

.link {
  color: #29e;
}

.activecaption {
  color: #fff;
  background-color: #000;
}

@media all and (-ms-high-contrast: none) {
  * {
    scrollbar-base-color: #000;
    scrollbar-face-color: #555;
    scrollbar-track-color: #111;
    scrollbar-arrow-color: #777;
  }

  button, input[type="button"], input[type="file"], input[type="submit"], input[type="reset"] {
    color: #fff;
    background-color: #191919;
    border: solid 1px #555;
  }

  button:hover, input[type="button"]:hover, input[type="file"]:hover, input[type="submit"]:hover, input[type="reset"]:hover {
    color: #fff;
    background-color: #555;
    border: solid 1px #777;
  }

  button:disabled, input[type="button"]:disabled {
    color: #777;
  }

  input:-ms-input-placeholder {
    color: #777;
  }
}
```

Regards,
